### ISSUE TITLE
Pretrained Effect Approximator for 32k/65k Width SAE (layer 12)

### ISSUE THREAD

**Issue by spfaul** [slavachalnev/SAE-TS#3]
I see in steer_cfgs there is an entry for GGB_65k and London65k, are there available pretrained Effect Approximators to experiment with for these examples? It would be greatly beneficial.

@slavachalnev

**Comment by slavachalnev** [comment]
Unfortunately no, I didn't train effect approximators the 65k SAE although in retrospect I should have done that as it wouldn't have added much compute cost. Sorry about that.

**Comment by slavachalnev** [comment]
The 65k entries in steer_cfgs were used for rotation_steer
